# frontend/netlify.toml

# Redirect rule for proxying API requests to the backend
[[redirects]]
  from = "/api/*"
  to = "https://explore-sphere-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {
    "Access-Control-Allow-Origin" = "https://6815d88501302c81f78830e5--explore-sphere.netlify.app"
    "Access-Control-Allow-Methods" = "GET, POST, PUT, DELETE, OPTIONS"
    "Access-Control-Allow-Headers" = "Content-Type, Authorization"
    "Access-Control-Allow-Credentials" = true
  }

# Redirect rule for serving the React single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200